% Errors in consequences

check08: trait
        introduces 
                0, 1:                           -> N
                s:                      N       -> N
                __+__, __*__, __/__:    N, N    -> N
                __<__:                  N, N    -> Bool
        implies 
                N generated by s                % no basis generator
                \forall i: A                    % undeclared sort
                        j			% undeclared operator
                converts -                      % undeclared operator
                converts / exempting i/0,       % missing quantifier
                                     0*0        % / not in term

