% Trait with errors when B is renamed to A

check13a: trait
	A tuple of left, right: B		% bad field sort
	introduces
		c:   -> A
		f: B -> A
		g: A -> B
	asserts 
		A generated by f		% no basis generator
		\forall c:B c:B = c:B		% variable/constant conflict
		\forall x:A, x:B		% repeated variable
			g(x) = x

