% Trait with generator and partition errors

check07: trait
	introduces 
		0:      		-> N
		s: 		N    	-> N
		__<__: 		N, N 	-> Bool
		__<__:  	A, A	-> Bool
		-__, __-: 	A	-> N
		f:		A	-> N
		f:		A	-> A
		g:		A	-> N
		g:		A	-> A
		0:		A	-> A
		0:			-> A
		h:			-> A
	asserts
		N generated by 0, s	% ok by range constraint for 0
		N generated by s1	% undeclared operator s1
		N generated by 0, h	% bad range for operator h
		N generated by -	% ambiguous operator -
		N generated by s	% no basis generator
		A generated by h, 0	% 0 is ambiguous because h is basis
		A generated by 0, h	% ditto
		A generated by 0	% ok because 0 must be basis
	asserts
		N partitioned by <	% ok by domain constraint for <
		N partitioned by >	% undeclared operator >
		N partitioned by f	% no op with domain constraint
		A partitioned by -	% ambiguous operator -
		A partitioned by f, g	% ambiguous operators f, g
		A partitioned by <, f	% f ambiguous because < has range ~= A
		A partitioned by f, <	% ditto
