% Sample trait to illustrate TeX output
% Junk in this comment #$%&~_\{}|<>^"
% Modified to work with init file from 2.3 document in Appendix II.

NatAndMore: TRAIT
    INCLUDES A, (B, C)(f, *)	% Nonsense
    ASSUMES D(a for b)		% More nonsense
    Color ENUMERATION OF red, white, blue
    NatColor UNION OF hue: Color, intensity: Nat
    Pair TUPLE OF first, second: Nat   % Test ; as a separator
    INTRODUCES
	0, 1:                      -> Nat
	s:                     Nat -> Nat
	+, *:             Nat, Nat -> Nat
	<, >:             Nat, Nat -> Bool
	__[__]:           Nat, Nat -> Nat  % Nonsense for test
	__{__;__}:   Nat, Nat, Nat -> Nat  % Nonsense for test
	__\<__\>:         Nat, Nat -> Nat  % Nonsense for test
	#:	          Nat, Nat -> Nat  % Nonsense for test 
    ASSERTS
	Nat GENERATED BY 0, s
	Nat PARTITIONED BY <
	\forall x, y, z: Nat
	    x + 0 = x				\eqsep
	    x + (y + 1) 
		= (x + y) 
		   + 1				\eqsep
	    x * 0 = 
		0				\eqsep
	    x > 0 => s(x) > 0			\eqsep
	    (x > 0 /\ y > 0) => (x + y) > 0	\eqsep
	    (x = y /\ y = z) => x = z
    IMPLIES
	SORT Nat GENERATED BY 0, 1, +
	SORT Nat partitioned BY >	    % test one lowercase keyword
	EQUATIONS
	    0 < 1
	\forall x', y', z': Nat		    % test ' as an idChar
	    (x' = 0) \/ (x' < 0) \/ (x' < 0)	\eqsep
	    ~(y' > 0 /\ y' < 0)			\eqsep
	    x' + 1 ~= z'
	CONVERTS +, *


%t This should be passed to LaTeX: \newpage

% This comment will not be indented correctly.

	
