/*
**
**	Copyright (c) MIT, 1990
**	All Rights Reserved.  Unpublished rights reserved under the copyright 
**	laws of the United States.
**
**++
**  FACILITY:  LSL Checker
**
**  MODULE DESCRIPTION:
**
**      FILENAME:   reduce.h
**
**	PURPOSE:    Interface to routines that process reductions from
**		    shift/reduce sequence generated by parser
**	
**
**  MODIFICATION HISTORY:
**
**      {0} McKeeman at Digital -- 90.04.20 -- original
**      {n} Who      at Where   -- yy.mm.dd -- What
**--
*/


/*
**
**  MACRO DEFINITIONS (none)
**
*/

/*
**
**  TYPEDEFS (none)
**
*/

/*
**
**  FUNCTION PROTOTYPES
**
*/

extern void		LSLGenReduce(LSLRuleCode rule);


/*
**
**  EXTERNAL VARIABLES (none)
**
*/
