StackBasics(E): trait
  % Essential LIFO operators
  introduces
    empty:             -> Stack[E] 
    push:  E, Stack[E] -> Stack[E]
    top:   Stack[E]    -> E
    pop:   Stack[E]    -> Stack[E]
  asserts
    sort Stack[E] generated by empty, push
    \forall e: E, stk: Stack[E]
      top(push(e, stk)) = e;
      pop(push(e, stk)) = stk;
  implies converts top, pop
    exempting top(empty), pop(empty)
